### ISSUE TITLE
Add prefixes and / or suffixes built-in

### ISSUE THREAD

**Issue by Mr-Xcoder** [muddyfish/PYKE#2]
There are lots of recent challenges regarding array-manipulation and these built-ins would be really helpful sometimes. Examples:

`[1, 2, 3, 4] -> [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]`
`"abcd" -> ["a", "ab", "abc", "abcd"]`

**Comment by muddyfish** [comment]
Feature added as `.>` and `.<`
